# Generated by Django 3.0.8 on 2020-09-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_auto_20200907_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='user',
        ),
    ]
