# Generated by Django 3.0.8 on 2020-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_auto_20200831_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
