# Generated by Django 3.0.8 on 2020-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_dairy_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='dairy',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
