# Generated by Django 3.0.8 on 2020-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_auto_20200831_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='description',
            field=models.TextField(),
        ),
    ]
